## 학습내용
<pre>
1-1
1-2 sparse 행렬
1-3 pandas 열 선택
</pre>

### 1-2 sparse 행렬
<pre>
희소 행렬(sparse matrix, 희박행렬)은 0을 많이 포함한 2차원 배열을 저장 시에 사용.
</pre>

In [2]:
from scipy import sparse
import numpy as np

# 대각선 원소는 1이고 나머지는 0인 2차원 Numpy 배열을 만든다.
eye = np.eye(4)
print("Numpy 배열 : \n{}".format(eye))

Numpy 배열 : 
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### 희소 행렬로 바꾸기

In [3]:
# Numpy 배열을 CSR 포맷의 SciPy 희소 행렬로 변환
# 0이 아닌 원소만 저장한다.
sparse_matrix = sparse.csr_matrix(eye)
print("SciPy의 CSR 행렬 :\n{}".format(sparse_matrix))

SciPy의 CSR 행렬 :
  (0, 0)	1.0
  (1, 1)	1.0
  (2, 2)	1.0
  (3, 3)	1.0


### 1-3 pandas 열 선택

In [4]:
import pandas as pd
train = pd.read_csv("D:/dataset/data_titanic/train.csv", index_col=["PassengerId"])
print(train.shape)
train.head()

(891, 11)


Survived  Pclass  \
PassengerId                     
1                   0       3   
2                   1       1   
3                   1       3   
4                   1       1   
5                   0       3   

                                                          Name     Sex   Age  \
PassengerId                                                                    
1                                      Braund, Mr. Owen Harris    male  22.0   
2            Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
3                                       Heikkinen, Miss. Laina  female  26.0   
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
5                                     Allen, Mr. William Henry    male  35.0   

             SibSp  Parch            Ticket     Fare Cabin Embarked  
PassengerId                                                          
1                1      0         A/5 21171   7.2500   NaN        S  
2                1      0          PC 17599  71.2833   C85        C  
3                0      0  STON/O2. 3101282   7.9250   NaN        S  
4                1      0            113803  53.1000  C123        S  
5                0      0            373450   8.0500   NaN        S

### Name에서 Age까지 선택

#### [df].loc[:, '열이름1':'열이름2']

In [7]:
train.loc[:, 'Name':'Age'][1:5]

Name     Sex   Age
PassengerId                                                                 
2            Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0
3                                       Heikkinen, Miss. Laina  female  26.0
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0
5                                     Allen, Mr. William Henry    male  35.0

### 01. 군집 알고리즘의 비교와 평가

## ARI 
<pre>
1(최적일 때)와 0(무작위로 분류될 때) 사이의 값을 제공한다. ARI(adjusted rand index)

(가) 무작위로 클러스터에 포인터를 할당하면 ARI는 0에 가까워진다.
(나) ARI 값의 범위를 -1~1 로 설명한다. 단, 최저값에 대한 근거를 찾을 수 없고, ARI 공식으로 분석하면 -0.5가 최저값으로 보인다.
(옮긴이 주석)
https://goo.gl/hdCYNe
(다) ARI NMI 같은 지표는 애플리케이션의 성능 평가가 아니라 알고리즘 개발할 때 도움이 된다.
</pre>